evsu_library/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('system.urls', namespace='system')),
    # {% url 'admin:polls_choice_add' %}
    # path('admin/system/outgoingtransaction/add/'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library_system/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('system.urls', namespace='system')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

system/urls.py
from django.urls import path, re_path
from system.forms import LoginForm
from system import views
from django.contrib.auth import views as auth_views

app_name = 'system'

urlpatterns = [
    path('', views.index, name='index'),
    path('qr/<str:pk>/', views.show_qr, name="show-qr"),
    path('login/',
         auth_views.LoginView.as_view(authentication_form=LoginForm, redirect_authenticated_user=True), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('accounts/verify/<str:id>/', views.verify_account_view, name='create'),
    path('accounts/send_verification/', views.send_verification, name='send_verification'),
    path('student_profile/<int:pk>/', views.StudentProfileUpdateView.as_view(), name='student_profile'),
    path('student/books/', views.BookListView.as_view(), name='books'),
    path('outgoingtransaction/create/', views.create_outgoing, name='outgoing_create'),
    path('incomingtransaction/create/', views.create_incoming, name='incoming_create'),
    path('admin/sms/', views.sms_view, name='sms'),
    re_path(
        r'^student-autocomplete/$',
        views.StudentAutocomplete.as_view(),
        name='student-autocomplete',
    ),
    path('admin/send_sms/', views.send_sms, name='send_sms'),
    path('admin/mark_as_paid/<int:id>/', views.mark_as_paid, name='mark_as_paid'),
    path('admin/mark_as_returned/<int:id>/', views.mark_as_returned, name='mark_as_returned'),
    path('admin/transaction_history/', views.TransactionHistoryListView.as_view(), name='transaction_history'),
    path('student/transaction_history/', views.StudentTransactionHistoryListView.as_view(), name='transaction_history_student'),
    path('admin/send_penalty_notification/', views.send_penalty_notification, name='send_penalty_notification')
]

templates/partials/_footer.html
<!-- Footer -->

<!-- <footer class="p-2 bg-white text-center fixed-bottom"><hr class="my-6 border-gray-200 sm:mx-auto lg:my-8"><span class="block text-sm text-gray-500 sm:text-center dark:text-gray-400">
    <p>&copy; {% now "Y" %} {{ app_title }} </p></span>
  </footer> -->



  <footer id="#footer" class=" fixed-bottom bg-white">
    <div class="container text-center">
      <span class="block text-sm text-gray-500 dark:text-gray-400">
        <p>&copy; {% now "Y" %} {{ app_title }} </p>
      </span>
    </div>
  </footer>

templates/partials/_navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'system:index' %}">
      <img src="{% static 'img/logo.png' %}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
      {{ app_title }}
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarText">
      {% if request.user.is_authenticated %}
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'system:index' %}">Home</a>
        </li>
        {% if user_id %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'system:student_profile' pk=user_id %}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'system:student_borrowed_books' pk=user_id %}">Borrowed Books</a>
        </li>
        {% endif %}
      </ul>
      {% endif %}

    <span class="navbar-text p-x5 text-white">
    {% if not request.user.is_authenticated %}
    
      <a href="{% url 'system:login' %}">Login</a>/
      <a href="{% url 'system:register' %}">Register</a>
    
    {% else %}
      {{request.user.email}}
      <a href="{% url 'system:logout' %}">Log out</a>
    {% endif %}
  </span>
    </div>
  </div>
</nav>